version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/scopesnap-web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/scopesnap-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
