"""
SnapAI — Model Download Script (runs on Railway container startup)
=======================================================================
Downloads AI model files from R2 if not already present in /app/models/.
Called by start.sh before uvicorn starts.

Model files:
  ONNX (from R2):  best_corrosion_v4.onnx, scopesnap_multiclass_v1.onnx
  PKL  (from git): scopesnap_sensor_model.pkl, scopesnap_label_encoder.pkl

ONNX files are generated by scripts/export_to_onnx.py (run on Modal once).

Exit codes:
    0 — critical PKL models present (server can start)
    1 — PKL model missing (server should NOT start)
"""
import os
import sys
from pathlib import Path

MODELS_DIR = Path(__file__).parent.parent / "models"

# Small PKL files — come from git (always present)
GIT_MODEL_FILES = [
    "scopesnap_sensor_model.pkl",
    "scopesnap_label_encoder.pkl",
]

# ONNX files — stored in R2, downloaded here at startup
R2_ONNX_FILES = [
    "best_corrosion_v4.onnx",
    "scopesnap_multiclass_v1.onnx",
]


def check_git_models() -> bool:
    missing = []
    for filename in GIT_MODEL_FILES:
        if not (MODELS_DIR / filename).exists():
            missing.append(filename)
    if missing:
        print(f"❌ Critical PKL files missing: {missing}")
        return False
    for f in GIT_MODEL_FILES:
        size_mb = (MODELS_DIR / f).stat().st_size / (1024 * 1024)
        print(f"  ✅ {f} ({size_mb:.2f} MB) — from git")
    return True


def download_onnx_from_r2() -> None:
    """Download ONNX model files from R2 using boto3."""
    account_id = os.environ.get("CLOUDFLARE_R2_ACCOUNT_ID", "")
    access_key = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY", "")
    secret_key = os.environ.get("CLOUDFLARE_R2_SECRET_KEY", "")
    bucket     = os.environ.get("CLOUDFLARE_R2_BUCKET", "")

    if not all([account_id, access_key, secret_key, bucket]):
        print("  ⚠️  R2 credentials not set — skipping ONNX download (YOLO disabled)")
        return

    try:
        import boto3
        s3 = boto3.client(
            "s3",
            endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name="auto",
        )
    except ImportError:
        print("  ⚠️  boto3 not available — skipping ONNX download")
        return

    for filename in R2_ONNX_FILES:
        dest = MODELS_DIR / filename
        if dest.exists():
            size_mb = dest.stat().st_size / (1024 * 1024)
            print(f"  ✅ {filename} ({size_mb:.1f} MB) — already present")
            continue

        r2_key = f"models/{filename}"
        print(f"  ⬇️  Downloading {filename} from R2 ({r2_key})...")
        try:
            tmp = dest.with_suffix(".tmp")
            s3.download_file(bucket, r2_key, str(tmp))
            tmp.rename(dest)
            size_mb = dest.stat().st_size / (1024 * 1024)
            print(f"  ✅ {filename} ({size_mb:.1f} MB) — downloaded")
        except Exception as e:
            print(f"  ⚠️  Could not download {filename}: {e}")
            print(f"      Run scripts/export_to_onnx.py on Modal to generate and upload it.")
            if tmp.exists():
                tmp.unlink()


def main():
    print("\n" + "=" * 55)
    print("  SnapAI — AI Model Initialization")
    print("=" * 55)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    print("\n📦 Checking PKL sensor model files (from git):")
    if not check_git_models():
        print("\n❌ Cannot start — XGBoost model files missing from git.")
        sys.exit(1)

    print("\n📡 Checking ONNX YOLO model files (from R2):")
    download_onnx_from_r2()

    print("\n📊 Final Model Status:")
    for filename in GIT_MODEL_FILES + R2_ONNX_FILES:
        path = MODELS_DIR / filename
        if path.exists():
            size_mb = path.stat().st_size / (1024 * 1024)
            print(f"  ✅ {filename} ({size_mb:.1f} MB)")
        else:
            status = "YOLO disabled — Gemini fallback active" if filename.endswith(".onnx") else "MISSING"
            print(f"  ⚠️  {filename} — {status}")

    print("=" * 55 + "\n")


if __name__ == "__main__":
    main()
