"""
ScopeSnap — Equipment Database Seed Script
Populates equipment_models with 50 entries (10 per major brand).
Run once during setup. Safe to re-run (uses INSERT OR IGNORE / upsert).

Usage: python scripts/seed_equipment_db.py
WP-03 deliverable.
"""

import asyncio
import sys
import os
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from db.database import AsyncSessionLocal, engine, Base
from db.models import EquipmentModel
from sqlalchemy import select
import uuid


EQUIPMENT_MODELS = [
    # ── CARRIER (10 models) ────────────────────────────────────────────────────
    {
        "brand": "Carrier",
        "model_series": "24ACC6",
        "model_pattern": r"24ACC6\d{2}[A-Z]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2011-2023",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "evap_coil", "issue": "formicary_corrosion", "onset_year": 5,
             "frequency": "34%", "regions": ["gulf_coast", "southeast"],
             "description": "Pinhole leaks in copper coil due to formicary corrosion from organic vapors"},
            {"component": "compressor", "issue": "copeland_scroll_failure", "onset_year": 10,
             "frequency": "12%", "regions": ["all"],
             "description": "Copeland scroll compressor bearing wear at high usage"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": ["25HCB648A003", "24ACC648A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "25HCB",
        "model_pattern": r"25HCB\d{3}[A-Z]\d{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 17.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2015-2023",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "reversing_valve", "issue": "stuck_valve", "onset_year": 7,
             "frequency": "8%", "regions": ["all"],
             "description": "Reversing valve sticking in heating or cooling mode"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "58MXA",
        "model_pattern": r"58MXA\d{3}[A-Z]{2}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "heat_exchanger", "issue": "cracking", "onset_year": 12,
             "frequency": "5%", "regions": ["all"],
             "description": "Secondary heat exchanger cracking can cause CO infiltration"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": ["58MTA080-14"],
    },
    {
        "brand": "Carrier",
        "model_series": "24ANB1",
        "model_pattern": r"24ANB1\d{2}[A-Z]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2008-2016",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": ["24ACC636A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "38AH",
        "model_pattern": r"38AH\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2005-2015",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "condenser_coil", "issue": "refrigerant_leak", "onset_year": 8,
             "frequency": "10%", "regions": ["coastal"],
             "description": "Condenser coil refrigerant leak at brazed joints"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "FB4C",
        "model_pattern": r"FB4C[A-Z]\d{3}[A-Z]",
        "equipment_type": "ac_unit",
        "seer_rating": 14.5,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2018",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "40RU",
        "model_pattern": r"40RU\d{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 15.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2012-2020",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "58CVA",
        "model_pattern": r"58CVA\d{3}[A-Z]{2}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2008-2018",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "inducer_motor", "issue": "bearing_wear", "onset_year": 10,
             "frequency": "7%", "regions": ["all"],
             "description": "Inducer motor bearing failure causes loud noise and shutdown"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "25HBC",
        "model_pattern": r"25HBC\d{3}[A-Z]\d{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 15.5,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2013-2021",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "GT-PFC",
        "model_pattern": r"GT-PFC\d{3}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2015-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "WWYYXXXXXXX", "week_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },

    # ── TRANE (10 models) ─────────────────────────────────────────────────────
    {
        "brand": "Trane",
        "model_series": "XR15",
        "model_pattern": r"4TTR[BCD]\d{3}[A-Z]\d+",
        "equipment_type": "ac_unit",
        "seer_rating": 15.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2012-2022",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "TXV_valve", "issue": "hunting", "onset_year": 5,
             "frequency": "9%", "regions": ["all"],
             "description": "Thermostatic expansion valve hunting causes temperature swings"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": ["4TTR6036L1000A"],
    },
    {
        "brand": "Trane",
        "model_series": "XR14",
        "model_pattern": r"4TTR[A]\d{3}[A-Z]\d+",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2020",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "XR16",
        "model_pattern": r"4TTR[E]\d{3}[A-Z]\d+",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2014-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "XV20i",
        "model_pattern": r"4TW[KL]\d{3}[A-Z]\d+",
        "equipment_type": "ac_unit",
        "seer_rating": 22.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "S8X1",
        "model_pattern": r"TUS[AB]\d{3}[A-Z]\d+",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "secondary_heat_exchanger", "issue": "cracking", "onset_year": 10,
             "frequency": "4%", "regions": ["all"],
             "description": "Secondary heat exchanger crack can cause CO leak"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "XR13",
        "model_pattern": r"2TTR[A-Z]\d{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-4",
        "manufacture_years": "2008-2018",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "XL16i",
        "model_pattern": r"4TWR[67]\d{3}[A-Z]\d+",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2012-2022",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "S9V2",
        "model_pattern": r"TUX[123][AB]\d{3}[A-Z]",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2013-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "4MXW6",
        "model_pattern": r"4MXW6\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": None,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2018-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "XB13",
        "model_pattern": r"2TWR[AB]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2006-2016",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYYWNN", "letter_pos": 0, "year_chars": [1, 2], "week_chars": [4, 5]},
        "replacement_models": [],
    },

    # ── LENNOX (10 models) ────────────────────────────────────────────────────
    {
        "brand": "Lennox",
        "model_series": "XC16",
        "model_pattern": r"16ACX\d{3}(-\d+)?",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "copper_tubing", "issue": "vibration_cracks", "onset_year": 6,
             "frequency": "6%", "regions": ["all"],
             "description": "Copper tubing cracks from vibration at specific mounting locations"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": ["16ACX036-230"],
    },
    {
        "brand": "Lennox",
        "model_series": "XP21",
        "model_pattern": r"16HPX\d{3}(-\d+)?",
        "equipment_type": "heat_pump",
        "seer_rating": 21.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2014-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "SL280",
        "model_pattern": r"SL28[0-9]{1,2}(UH|DF|V)\d{2}[A-Z]\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "XC13",
        "model_pattern": r"13ACX\d{3}(-\d+)?",
        "equipment_type": "ac_unit",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2008-2019",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": ["16ACX036-230"],
    },
    {
        "brand": "Lennox",
        "model_series": "XP14",
        "model_pattern": r"14HPX\d{3}(-\d+)?",
        "equipment_type": "heat_pump",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-4",
        "manufacture_years": "2008-2018",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "ML195",
        "model_pattern": r"19[0-9]{4}[A-Z]{2}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2012-2022",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "XC21",
        "model_pattern": r"21ACX\d{3}(-\d+)?",
        "equipment_type": "ac_unit",
        "seer_rating": 21.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "EL16XC1",
        "model_pattern": r"EL16XC1-\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2018-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "XP25",
        "model_pattern": r"25HPX\d{3}(-\d+)?",
        "equipment_type": "heat_pump",
        "seer_rating": 23.5,
        "tonnage_range": "2-5",
        "manufacture_years": "2017-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "SL297",
        "model_pattern": r"SL297(NV|UH|DF)\d{2}[A-Z]\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2015-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "YYWWXXXXXXX", "year_chars": [0, 1], "week_chars": [2, 3]},
        "replacement_models": [],
    },

    # ── GOODMAN (10 models) ───────────────────────────────────────────────────
    {
        "brand": "Goodman",
        "model_series": "GSX14",
        "model_pattern": r"GSX14\d{3}[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 14,
        "known_issues": [
            {"component": "compressor", "issue": "capacitor_failure", "onset_year": 4,
             "frequency": "18%", "regions": ["all"],
             "description": "Run capacitor failure — common at 4-7 years and inexpensive to fix"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": ["GSX160361"],
    },
    {
        "brand": "Goodman",
        "model_series": "GSX16",
        "model_pattern": r"GSX16\d{3}[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 14,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GMEC96",
        "model_pattern": r"GMEC96\d{4}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2023",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSH13",
        "model_pattern": r"GSH13\d{3}[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-4",
        "manufacture_years": "2006-2015",
        "avg_lifespan_years": 14,
        "known_issues": [
            {"component": "reversing_valve", "issue": "failure", "onset_year": 7,
             "frequency": "12%", "regions": ["all"],
             "description": "Reversing valve failure — stuck in heating or cooling mode"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": ["DSZC160361"],
    },
    {
        "brand": "Goodman",
        "model_series": "DSZC16",
        "model_pattern": r"DSZC16\d{3}[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2014-2023",
        "avg_lifespan_years": 14,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSXC18",
        "model_pattern": r"GSXC18\d{3}[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 18.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 14,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GMVC95",
        "model_pattern": r"GMVC95\d{4}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSX13",
        "model_pattern": r"GSX13\d{3}[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2008-2017",
        "avg_lifespan_years": 14,
        "known_issues": [
            {"component": "evap_coil", "issue": "corrosion", "onset_year": 5,
             "frequency": "22%", "regions": ["coastal", "gulf_coast"],
             "description": "Formicary corrosion on aluminum evaporator coil — common near saltwater"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "DSZC18",
        "model_pattern": r"DSZC18\d{3}[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 18.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 14,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GMSS92",
        "model_pattern": r"GMSS92\d{4}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2008-2018",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "LYWWXXXXXX", "letter_pos": 0, "year_pos": 1, "week_chars": [2, 3]},
        "replacement_models": [],
    },

    # ── RHEEM (10 models) ─────────────────────────────────────────────────────
    {
        "brand": "Rheem",
        "model_series": "RA14",
        "model_pattern": r"RA14AZ\d{3}J[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "condenser_fan_motor", "issue": "failure", "onset_year": 5,
             "frequency": "10%", "regions": ["all"],
             "description": "Condenser fan motor failure — causes overheating and compressor damage if not addressed"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": ["RA16AZ036JK"],
    },
    {
        "brand": "Rheem",
        "model_series": "RA16",
        "model_pattern": r"RA16AZ\d{3}J[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2013-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RPGE",
        "model_pattern": r"RPGE-\d{3}[A-Z]\d{3}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "MMYYNNNNN", "month_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RP14",
        "model_pattern": r"RP14AZ\d{3}J[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2020",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RP16",
        "model_pattern": r"RP16AZ\d{3}J[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2013-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RA18",
        "model_pattern": r"RA18AZ\d{3}J[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 18.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RGPJ",
        "model_pattern": r"RGPJ-\d{3}[A-Z]\d{3}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2014-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "MMYYNNNNN", "month_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RA13",
        "model_pattern": r"RA13AZ\d{3}J[A-Z]?",
        "equipment_type": "ac_unit",
        "seer_rating": 13.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2007-2016",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "evap_coil", "issue": "aluminum_corrosion", "onset_year": 6,
             "frequency": "14%", "regions": ["coastal"],
             "description": "Aluminum evaporator coil corrosion near coastal areas"}
        ],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": ["RA14AZ036JK"],
    },
    {
        "brand": "Rheem",
        "model_series": "RP18",
        "model_pattern": r"RP18AZ\d{3}J[A-Z]?",
        "equipment_type": "heat_pump",
        "seer_rating": 18.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2023",
        "avg_lifespan_years": 15,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "FYYWNNNNN", "prefix": "F", "year_chars": [1, 2], "week_chars": [3, 4]},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RSPM",
        "model_pattern": r"RSPM-\d{3}[A-Z]\d{3}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2018-2023",
        "avg_lifespan_years": 20,
        "known_issues": [],
        "recalls": [],
        "serial_decode_pattern": {"format": "MMYYNNNNN", "month_chars": [0, 1], "year_chars": [2, 3]},
        "replacement_models": [],
    },
]


async def seed_equipment_db():
    """Insert all 50 equipment models. Skip existing ones (by brand+model_series)."""
    async with AsyncSessionLocal() as db:
        created = 0
        skipped = 0

        for model_data in EQUIPMENT_MODELS:
            # Check if already exists
            result = await db.execute(
                select(EquipmentModel).where(
                    EquipmentModel.brand == model_data["brand"],
                    EquipmentModel.model_series == model_data["model_series"],
                )
            )
            existing = result.scalar_one_or_none()

            if existing:
                skipped += 1
                continue

            model = EquipmentModel(
                id=str(uuid.uuid4()),
                brand=model_data["brand"],
                model_series=model_data["model_series"],
                model_pattern=model_data.get("model_pattern"),
                equipment_type=model_data["equipment_type"],
                seer_rating=model_data.get("seer_rating"),
                tonnage_range=model_data.get("tonnage_range"),
                manufacture_years=model_data.get("manufacture_years"),
                avg_lifespan_years=model_data.get("avg_lifespan_years"),
                known_issues=model_data.get("known_issues", []),
                recalls=model_data.get("recalls", []),
                serial_decode_pattern=model_data.get("serial_decode_pattern"),
                replacement_models=model_data.get("replacement_models", []),
                total_assessments=0,
            )
            db.add(model)
            created += 1

        await db.commit()
        print(f"Equipment DB seed complete: {created} created, {skipped} skipped")
        return created


if __name__ == "__main__":
    asyncio.run(seed_equipment_db())
