/**
 * SnapAI -- Public Terms of Service page. Linked from the public footer.
 * CONTENT SOURCE: ScopeSnapAI/SnapAI_Legal_Framework_ToS_and_Disclaimers_v1_DRAFT.md
 * Renders LAYER 2 -- Contractor Terms of Service (Sections 1-16) verbatim.
 * Do NOT edit legal wording without Alfred (US HVAC counsel) sign-off.
 */
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-surface-bg text-text-primary">
      <div className="max-w-2xl mx-auto px-6 py-12">
        <div className="mb-8">
          <a href="/tech" className="text-brand-green text-sm font-semibold hover:underline">← Back to SnapAI</a>
          <h1 className="text-3xl font-bold mt-4 mb-2">Terms of Service</h1>
          <p className="text-text-secondary text-sm">Last updated: July 6, 2026</p>
          <p className="text-text-secondary text-sm italic mt-1">Draft pending final legal review (Alfred, US HVAC counsel). Not yet effective.</p>
        </div>
        <div className="prose prose-sm max-w-none space-y-6 text-text-primary">
          <p className="text-sm text-text-secondary leading-relaxed">
            These Terms of Service govern use of SnapAI by licensed HVAC contractors.
          </p>

          <section>
            <h2 className="text-lg font-bold mb-2">1. Definitions</h2>
            <ul className="text-sm text-text-secondary leading-relaxed space-y-2">
              <li><strong className="text-text-primary">&quot;SnapAI&quot;</strong> or <strong className="text-text-primary">&quot;we&quot;</strong> — the software service operated by [SnapAI legal entity]</li>
              <li><strong className="text-text-primary">&quot;Contractor&quot;</strong> or <strong className="text-text-primary">&quot;you&quot;</strong> — the licensed HVAC service provider entering this agreement</li>
              <li><strong className="text-text-primary">&quot;Output&quot;</strong> — any recommendation, fault card, diagnostic suggestion, or report generated by the SnapAI service</li>
              <li><strong className="text-text-primary">&quot;Homeowner&quot;</strong> — the end customer of the Contractor&apos;s service</li>
              <li><strong className="text-text-primary">&quot;License&quot;</strong> — Contractor&apos;s active state HVAC contractor license</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">2. Nature of the service</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">2.1 Decision-support only.</strong> SnapAI is a diagnostic decision-support tool. It is not a diagnostic device, is not FDA or EPA certified, is not a substitute for professional judgment, and does not perform any service, installation, repair, or safety inspection.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">2.2 Not a warranty of accuracy.</strong> SnapAI Outputs are probabilistic recommendations based on limited input data (photographs, sensor readings, user descriptions). SnapAI makes no representation that any Output is complete, accurate, or safe to act on without independent professional verification.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">2.3 Not a replacement for professional judgment.</strong> All Outputs are advisory. The licensed Contractor is at all times the sole decision-maker regarding diagnosis, service action, repair recommendation, and safety assessment.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">3. Contractor obligations</h2>
            <p className="text-sm text-text-secondary leading-relaxed">Contractor agrees that:</p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.1</strong> Contractor holds a current, valid HVAC contractor license in the jurisdiction where services are performed.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.2</strong> Contractor will independently verify every Output before acting on it — including but not limited to:
            </p>
            <ul className="text-sm text-text-secondary leading-relaxed space-y-2">
              <li>Visual inspection of relevant components</li>
              <li>Independent instrument readings where safety-critical</li>
              <li>Application of professional judgment to reject any Output that conflicts with observed conditions</li>
              <li>Independent verification of any safety-related finding</li>
            </ul>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.3</strong> Contractor will not act on any Output relating to combustion, heat exchanger, carbon monoxide, gas leak, or fire safety without independent verification using industry-standard combustion analysis equipment and visual inspection consistent with NFPA 54 / IFGC.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.4</strong> Contractor will not represent to any Homeowner that SnapAI has &quot;diagnosed&quot; any condition. All Homeowner-facing communications will describe Outputs as &quot;preliminary findings requiring professional verification.&quot;
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.5</strong> Contractor will not present SnapAI Outputs to Homeowners as authoritative safety certifications.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">3.6</strong> Contractor is solely responsible for compliance with all applicable federal, state, and local laws, including but not limited to EPA §608 refrigerant handling, NFPA 54 gas code, state licensing requirements, and consumer protection laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">4. License grant</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">4.1 Limited license.</strong> SnapAI grants Contractor a limited, non-exclusive, non-transferable, revocable license to use the SnapAI service for professional HVAC diagnostic support during the term of this agreement.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">4.2 Restrictions.</strong> Contractor shall not: (a) resell, sublicense, or transfer the service; (b) reverse-engineer or attempt to derive the underlying diagnostic models; (c) use the service for any purpose other than professional HVAC diagnostic support; (d) misrepresent SnapAI&apos;s capabilities to any third party.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">5. Warranties and disclaimers</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">5.1 NO WARRANTY.</strong> THE SNAPAI SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, OR NON-INFRINGEMENT.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">5.2 NO DIAGNOSTIC CERTIFICATION.</strong> SNAPAI IS NOT A CERTIFIED DIAGNOSTIC DEVICE. SNAPAI OUTPUTS ARE NOT MEDICAL, ENGINEERING, OR SAFETY CERTIFICATIONS. NO SNAPAI OUTPUT SHALL BE CONSTRUED AS PROFESSIONAL CERTIFICATION OF HVAC EQUIPMENT SAFETY OR FITNESS.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">5.3 NO WARRANTY OF UPTIME.</strong> SnapAI does not warrant uninterrupted or error-free operation.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">5.4 NO WARRANTY OF MODEL ACCURACY.</strong> SnapAI&apos;s underlying diagnostic models are probabilistic. SnapAI makes no representation regarding the false-positive or false-negative rate of any Output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">6. Limitation of liability</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">6.1 LIABILITY CAP.</strong> IN NO EVENT SHALL SNAPAI&apos;S TOTAL LIABILITY TO CONTRACTOR ARISING FROM OR RELATING TO THIS AGREEMENT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY CONTRACTOR TO SNAPAI IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY, OR (B) TEN THOUSAND DOLLARS ($10,000).
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">6.2 NO CONSEQUENTIAL DAMAGES.</strong> IN NO EVENT SHALL SNAPAI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST DATA, BUSINESS INTERRUPTION, LOSS OF GOODWILL, OR ANY OTHER COMMERCIAL DAMAGES.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">6.3 EXCLUSIONS.</strong> Sections 6.1 and 6.2 shall apply to the maximum extent permitted by law, notwithstanding any failure of essential purpose of any limited remedy. The parties acknowledge that these limitations reflect the fees paid and are a fundamental basis of the bargain.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">7. Indemnification</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">7.1 Contractor indemnification.</strong> Contractor shall defend, indemnify, and hold harmless SnapAI, its officers, employees, contractors, and affiliates from and against any and all claims, demands, actions, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising from or relating to:
            </p>
            <ul className="text-sm text-text-secondary leading-relaxed space-y-2">
              <li>(a) Contractor&apos;s use of any Output</li>
              <li>(b) Contractor&apos;s service, diagnosis, repair, or safety inspection of any HVAC equipment</li>
              <li>(c) Any injury, illness, property damage, or death arising from Contractor&apos;s HVAC services</li>
              <li>(d) Any misrepresentation by Contractor of SnapAI&apos;s capabilities to any Homeowner or third party</li>
              <li>(e) Contractor&apos;s failure to independently verify any Output</li>
              <li>(f) Contractor&apos;s failure to comply with applicable laws, regulations, or licensing requirements</li>
              <li>(g) Any claim by a Homeowner arising from work performed by Contractor</li>
              <li>(h) Contractor&apos;s breach of any provision of this Agreement</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">8. Class action waiver</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">8.1 CLASS ACTION WAIVER.</strong> CONTRACTOR AGREES THAT ANY DISPUTE ARISING FROM OR RELATING TO THIS AGREEMENT OR CONTRACTOR&apos;S USE OF THE SNAPAI SERVICE SHALL BE RESOLVED SOLELY ON AN INDIVIDUAL BASIS. CONTRACTOR EXPRESSLY WAIVES ANY RIGHT TO PARTICIPATE IN ANY CLASS ACTION, CONSOLIDATED ACTION, OR REPRESENTATIVE ACTION AGAINST SNAPAI.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">9. Mandatory arbitration</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">9.1 Binding arbitration.</strong> Any dispute arising from or relating to this Agreement shall be resolved exclusively by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">9.2 Venue.</strong> Arbitration shall be conducted in Harris County, Texas.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">9.3 Costs.</strong> Each party shall bear its own attorneys&apos; fees and costs of arbitration, except as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">10. Governing law</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              This Agreement shall be governed by and construed under the laws of the State of Texas, without regard to conflict-of-laws principles.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">11. Term and termination</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">11.1 Term.</strong> This Agreement is effective on Contractor&apos;s acceptance and continues until terminated.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">11.2 Termination for convenience.</strong> Either party may terminate this Agreement upon thirty (30) days written notice.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">11.3 Termination for breach.</strong> SnapAI may terminate this Agreement immediately upon Contractor&apos;s material breach.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">11.4 Effect of termination.</strong> Contractor&apos;s obligations under Sections 5, 6, 7, 8, 9, 10, 12, 13, and 14 shall survive termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">12. Data ownership and audit trail</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">12.1 Audit trail.</strong> Contractor acknowledges that SnapAI maintains an audit trail of all diagnostic activities, including without limitation input data, generated Outputs, timestamps, and Contractor identity, for a period of not less than four (4) years.
            </p>
            <p className="text-sm text-text-secondary leading-relaxed">
              <strong className="text-text-primary">12.2 Cooperation with legal process.</strong> Contractor agrees that SnapAI may disclose audit trail data as required by law, regulation, subpoena, or court order.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">13. Modification</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              SnapAI reserves the right to modify this Agreement upon thirty (30) days notice. Continued use after notice constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">14. Assignment</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              Contractor may not assign this Agreement without SnapAI&apos;s prior written consent. SnapAI may assign this Agreement at its sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">15. Severability</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              If any provision of this Agreement is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">16. Entire agreement</h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              This Agreement constitutes the entire agreement between the parties and supersedes all prior agreements, understandings, or communications.
            </p>
          </section>

          <section>
            <p className="text-sm text-text-secondary leading-relaxed">
              Questions:{" "}
              <a href="mailto:hello@mainnov.tech" className="text-brand-green font-semibold hover:underline">hello@mainnov.tech</a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
