"""
RW-05 — Equipment Model Seed Data
50 real HVAC equipment models: 5 brands × 10 models each.
Sources: manufacturer spec sheets, AHRI directory, industry publications.

Run:  python -m db.seeds.equipment_seed
"""

import sys, os, asyncio
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from db.database import AsyncSessionLocal
from db.models import EquipmentModel

# ─────────────────────────────────────────────────────────────────────────────
# Raw data — 50 models across 5 brands
# Fields: brand, model_series, model_pattern, equipment_type,
#         seer_rating, tonnage_range, manufacture_years, avg_lifespan_years,
#         known_issues, serial_decode_pattern, replacement_models
# ─────────────────────────────────────────────────────────────────────────────
EQUIPMENT_MODELS = [

    # ──────────────────────────────────────────────────────────────────────────
    # CARRIER (10 models)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "brand": "Carrier",
        "model_series": "24ACC6",
        "model_pattern": r"24ACC6\d{2}[A-Z]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "evap_coil", "issue": "formicary_corrosion",
             "onset_year": 6, "frequency": "28%",
             "regions": ["gulf_coast", "florida", "southeast"],
             "notes": "Copper coil pitting from formic acid in modern homes"},
            {"component": "TXV_valve", "issue": "hunting_or_failure",
             "onset_year": 8, "frequency": "12%"},
        ],
        "serial_decode_pattern": {
            "year_chars": [3, 4],
            "year_format": "2-digit",   # '14' = 2014
            "week_chars": [5, 6],
            "example": "2314A12345 → 2023, week 14"
        },
        "replacement_models": ["24ACC636A003", "24VNA636A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "24VNA9",
        "model_pattern": r"24VNA9\d{2}[A-Z]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 24.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2018-2024",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "inverter_board", "issue": "surge_damage",
             "onset_year": 5, "frequency": "9%",
             "notes": "Variable-speed drive board sensitive to power spikes"},
        ],
        "serial_decode_pattern": {
            "year_chars": [3, 4],
            "year_format": "2-digit",
            "week_chars": [5, 6],
        },
        "replacement_models": ["24VNA936A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "58STA",
        "model_pattern": r"58STA\d{3}[A-Z]{2}\d{4}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2020",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "draft_inducer", "issue": "bearing_wear",
             "onset_year": 10, "frequency": "22%"},
            {"component": "heat_exchanger", "issue": "crack",
             "onset_year": 15, "frequency": "8%",
             "notes": "Safety critical — CO risk. Check with mirror & flashlight."},
        ],
        "serial_decode_pattern": {
            "year_chars": [0, 3],
            "year_format": "4-digit",
        },
        "replacement_models": ["58CVA080-12"],
    },
    {
        "brand": "Carrier",
        "model_series": "25HCB6",
        "model_pattern": r"25HCB6\d{2}[A-Z]\d{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2014-2023",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "reversing_valve", "issue": "stuck_or_leak",
             "onset_year": 7, "frequency": "15%"},
            {"component": "defrost_board", "issue": "failure",
             "onset_year": 9, "frequency": "11%"},
        ],
        "serial_decode_pattern": {"year_chars": [3, 4], "year_format": "2-digit"},
        "replacement_models": ["25VNA636A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "40MBFQ",
        "model_pattern": r"40MBFQ\d{3}[A-Z]\d{3}",
        "equipment_type": "air_handler",
        "seer_rating": None,
        "tonnage_range": "2-5",
        "manufacture_years": "2015-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "blower_motor", "issue": "capacitor_failure",
             "onset_year": 6, "frequency": "18%"},
        ],
        "serial_decode_pattern": {"year_chars": [3, 4], "year_format": "2-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "WSHP038",
        "model_pattern": r"WSHP038[A-Z]+\d{6}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "3",
        "manufacture_years": "2008-2016",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "refrigerant_circuit", "issue": "leak_at_brazed_joints",
             "onset_year": 12, "frequency": "20%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["24ACC636A003"],
    },
    {
        "brand": "Carrier",
        "model_series": "48TF",
        "model_pattern": r"48TF\d{3}[A-Z]{2}\d{6}",
        "equipment_type": "packaged_unit",
        "seer_rating": 14.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2005-2018",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "condenser_coil", "issue": "hail_damage_fins",
             "onset_year": 5, "frequency": "14%", "regions": ["texas", "oklahoma"]},
            {"component": "gas_valve", "issue": "sticking",
             "onset_year": 12, "frequency": "9%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["50XCQ006-A"],
    },
    {
        "brand": "Carrier",
        "model_series": "24ANA1",
        "model_pattern": r"24ANA1\d{2}[A-Z]\d{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 18.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {"year_chars": [3, 4], "year_format": "2-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "58TP",
        "model_pattern": r"58TP\d{3}[A-Z]{2}\d{4}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2015-2024",
        "avg_lifespan_years": 22,
        "known_issues": [
            {"component": "ignitor", "issue": "silicon_nitride_crack",
             "onset_year": 5, "frequency": "16%"},
        ],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Carrier",
        "model_series": "WPHF",
        "model_pattern": r"WPHF\d{3}[A-Z]+\d{6}",
        "equipment_type": "heat_pump",
        "seer_rating": 17.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2019-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # TRANE (10 models)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "brand": "Trane",
        "model_series": "4TTR6",
        "model_pattern": r"4TTR6\d{3}[A-Z]\d{4}[A-Z]",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 16,
        "known_issues": [
            {"component": "spinalok_fin", "issue": "fin_corrosion",
             "onset_year": 7, "frequency": "19%",
             "regions": ["gulf_coast", "southeast", "hawaii"],
             "notes": "Trane's aluminum fin on copper coil — galvanic corrosion accelerates in humid/salt air"},
            {"component": "compressor", "issue": "scroll_failure",
             "onset_year": 10, "frequency": "8%"},
        ],
        "serial_decode_pattern": {
            "year_chars": [0, 3],
            "year_format": "4-digit",
            "example": "2016... → manufactured 2016"
        },
        "replacement_models": ["4TTR6036J1000A", "XR16 4TTR6036"],
    },
    {
        "brand": "Trane",
        "model_series": "XV20i",
        "model_pattern": r"4TYZ\d{4}[A-Z]\d{4}[A-Z]",
        "equipment_type": "ac_unit",
        "seer_rating": 22.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "communicating_board", "issue": "firmware_lockup",
             "onset_year": 4, "frequency": "7%",
             "notes": "Trane TruComfort wiring faults — requires Nexia gateway reset"},
        ],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "TUD2",
        "model_pattern": r"TUD2[A-Z]\d{6}[A-Z]\d{4}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2009-2021",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "pressure_switch", "issue": "hose_clog",
             "onset_year": 4, "frequency": "25%",
             "notes": "PVC condensate hose clogs — low error code first symptom"},
            {"component": "heat_exchanger", "issue": "crack_at_secondary",
             "onset_year": 14, "frequency": "6%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["S9X2B080D4PSA"],
    },
    {
        "brand": "Trane",
        "model_series": "XR15",
        "model_pattern": r"4TTR5\d{3}[A-Z]\d{4}[A-Z]",
        "equipment_type": "ac_unit",
        "seer_rating": 15.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 16,
        "known_issues": [
            {"component": "capacitor", "issue": "premature_failure",
             "onset_year": 5, "frequency": "31%",
             "notes": "Run capacitor derates faster in high-ambient climates"},
        ],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": ["4TTR6036J1000A"],
    },
    {
        "brand": "Trane",
        "model_series": "4TWR6",
        "model_pattern": r"4TWR6\d{3}[A-Z]\d{4}[A-Z]",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "reversing_valve", "issue": "partial_stick",
             "onset_year": 7, "frequency": "13%"},
        ],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "YCD",
        "model_pattern": r"YCD\d{3}[A-Z]\d{2}M\d{5}",
        "equipment_type": "packaged_unit",
        "seer_rating": 13.0,
        "tonnage_range": "3-10",
        "manufacture_years": "2005-2018",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "economizer", "issue": "actuator_failure",
             "onset_year": 6, "frequency": "22%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "S8X1",
        "model_pattern": r"S8X1[A-Z]\d{6}[A-Z]\d{4}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 22,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "TAM7",
        "model_pattern": r"TAM7[A-Z]\d{4}[A-Z]\d{5}",
        "equipment_type": "air_handler",
        "seer_rating": None,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "evap_coil", "issue": "leak_at_distributor",
             "onset_year": 8, "frequency": "10%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "4TXK6",
        "model_pattern": r"4TXK6\d{3}[A-Z]\d{4}[A-Z]",
        "equipment_type": "ac_unit",
        "seer_rating": 20.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2020-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Trane",
        "model_series": "RAUL",
        "model_pattern": r"RAUL\d{3}[A-Z]{3}\d{5}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "3-25",
        "manufacture_years": "2008-2020",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "scroll_compressor", "issue": "liquid_slugging",
             "onset_year": 8, "frequency": "11%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # LENNOX (10 models)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "brand": "Lennox",
        "model_series": "XC21",
        "model_pattern": r"XC21-\d{3}-\d{3}-\d{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 21.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2014-2024",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "icomfort_communicating_board", "issue": "comm_error",
             "onset_year": 4, "frequency": "14%",
             "notes": "Lennox iComfort wiring — loose 4-wire comm cable common cause"},
            {"component": "TXV_valve", "issue": "hunting",
             "onset_year": 7, "frequency": "8%"},
        ],
        "serial_decode_pattern": {
            "year_chars": [3, 6],
            "year_format": "4-digit",
            "example": "5820  → 2020, week 58"
        },
        "replacement_models": ["XC21-060-230-01"],
    },
    {
        "brand": "Lennox",
        "model_series": "XP25",
        "model_pattern": r"XP25-\d{3}-\d{3}-\d{2}",
        "equipment_type": "heat_pump",
        "seer_rating": 23.5,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "SL280",
        "model_pattern": r"SL280[A-Z]{2}\d{6}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "inducer_motor", "issue": "worn_bearings_noise",
             "onset_year": 8, "frequency": "20%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "XC16",
        "model_pattern": r"XC16-\d{3}-\d{3}-\d{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 16,
        "known_issues": [
            {"component": "capacitor", "issue": "bulge_or_leak",
             "onset_year": 5, "frequency": "26%",
             "notes": "Capacitor derating in southern US — check microfarad annually"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["XC21-060-230-01"],
    },
    {
        "brand": "Lennox",
        "model_series": "EL296V",
        "model_pattern": r"EL296V[A-Z]{2}\d{6}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2008-2020",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "secondary_heat_exchanger", "issue": "condensate_crack",
             "onset_year": 12, "frequency": "9%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["SL280NV110P48C"],
    },
    {
        "brand": "Lennox",
        "model_series": "XP20",
        "model_pattern": r"XP20-\d{3}-\d{3}-\d{2}",
        "equipment_type": "heat_pump",
        "seer_rating": 20.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2014-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "XC14",
        "model_pattern": r"XC14-\d{3}-\d{3}-\d{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 16,
        "known_issues": [
            {"component": "Schrader_valve", "issue": "slow_leak",
             "onset_year": 6, "frequency": "12%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["XC16-036-230-01"],
    },
    {
        "brand": "Lennox",
        "model_series": "CBX40",
        "model_pattern": r"CBX40UHV-\d{3}-\d{3}-\d{2}",
        "equipment_type": "air_handler",
        "seer_rating": None,
        "tonnage_range": "2-5",
        "manufacture_years": "2014-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "blower_wheel", "issue": "dust_buildup_imbalance",
             "onset_year": 5, "frequency": "17%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "ML14XC1",
        "model_pattern": r"ML14XC1-\d{3}-\d{3}-\d{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 17.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2018-2024",
        "avg_lifespan_years": 17,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Lennox",
        "model_series": "SL297NV",
        "model_pattern": r"SL297NV\d{6}\d{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2020-2024",
        "avg_lifespan_years": 22,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # GOODMAN / AMANA (10 models)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "brand": "Goodman",
        "model_series": "GSXC18",
        "model_pattern": r"GSXC18\d{6}[A-Z]{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 18.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2015-2024",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "Copeland_scroll_compressor", "issue": "tight_or_locked_rotor",
             "onset_year": 6, "frequency": "11%",
             "notes": "Goodman units have industry-leading warranty but labor not included; compressor replacements costly"},
        ],
        "serial_decode_pattern": {
            "year_chars": [0, 3],
            "year_format": "4-digit",
        },
        "replacement_models": ["GSXC180361"],
    },
    {
        "brand": "Goodman",
        "model_series": "GSX14",
        "model_pattern": r"GSX14\d{6}[A-Z]{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2008-2022",
        "avg_lifespan_years": 14,
        "known_issues": [
            {"component": "contactor", "issue": "pitted_contacts",
             "onset_year": 5, "frequency": "28%",
             "notes": "High cycling rates in hot climates accelerate contact wear"},
            {"component": "drain_pan", "issue": "crack_or_overflow",
             "onset_year": 8, "frequency": "13%"},
        ],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": ["GSXC180361"],
    },
    {
        "brand": "Goodman",
        "model_series": "GCES96",
        "model_pattern": r"GCES96\d{6}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "gas_valve", "issue": "sticking_closed",
             "onset_year": 7, "frequency": "9%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSXH5",
        "model_pattern": r"GSXH5\d{6}[A-Z]{2}",
        "equipment_type": "ac_unit",
        "seer_rating": 15.2,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2022-2024",
        "avg_lifespan_years": 16,
        "known_issues": [],
        "serial_decode_pattern": {"year_chars": [0, 3], "year_format": "4-digit"},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "AMVC96",
        "model_pattern": r"AMVC96\d{6}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 22,
        "known_issues": [
            {"component": "variable_speed_blower", "issue": "control_board_failure",
             "onset_year": 6, "frequency": "7%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "ARUF",
        "model_pattern": r"ARUF\d{2}[A-Z]\d{2}[A-Z]{2}",
        "equipment_type": "air_handler",
        "seer_rating": None,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2024",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "metering_device", "issue": "orifice_size_mismatch_installer_error",
             "onset_year": 0, "frequency": "8%",
             "notes": "Wrong orifice installed at commissioning — check superheat"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSZH6",
        "model_pattern": r"GSZH6\d{6}[A-Z]{2}",
        "equipment_type": "heat_pump",
        "seer_rating": 16.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2022-2024",
        "avg_lifespan_years": 16,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Goodman",
        "model_series": "GSZ14",
        "model_pattern": r"GSZ14\d{6}[A-Z]{2}",
        "equipment_type": "heat_pump",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "defrost_control", "issue": "lockout_in_cold_snap",
             "onset_year": 6, "frequency": "10%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["GSZH60361"],
    },
    {
        "brand": "Goodman",
        "model_series": "GCSS92",
        "model_pattern": r"GCSS92\d{6}[A-Z]{2}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2008-2018",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "heat_exchanger", "issue": "rust_perforation",
             "onset_year": 12, "frequency": "7%", "regions": ["humid_south"]},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["GCES960603BX"],
    },
    {
        "brand": "Goodman",
        "model_series": "DSZC18",
        "model_pattern": r"DSZC18\d{6}[A-Z]{2}",
        "equipment_type": "heat_pump",
        "seer_rating": 18.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 17,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # RHEEM / RUUD (10 models)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "brand": "Rheem",
        "model_series": "RA18AZ",
        "model_pattern": r"RA18AZ-\d{3}JCZ",
        "equipment_type": "ac_unit",
        "seer_rating": 20.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2018-2024",
        "avg_lifespan_years": 18,
        "known_issues": [
            {"component": "variable_speed_compressor", "issue": "soft_start_fault",
             "onset_year": 4, "frequency": "6%",
             "notes": "Rheem EcoNet fault code E9 — check control board firmware version"},
        ],
        "serial_decode_pattern": {
            "year_chars": [4, 7],
            "year_format": "4-digit",
            "example": "F123F2019A01234 → 2019"
        },
        "replacement_models": ["RA20AZ-036JCZ"],
    },
    {
        "brand": "Rheem",
        "model_series": "RA14AZ",
        "model_pattern": r"RA14AZ-\d{3}JCZ",
        "equipment_type": "ac_unit",
        "seer_rating": 15.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2022-2024",
        "avg_lifespan_years": 16,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RPRL",
        "model_pattern": r"RPRL-\d{3}[A-Z]{3}",
        "equipment_type": "ac_unit",
        "seer_rating": 14.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2006-2018",
        "avg_lifespan_years": 15,
        "known_issues": [
            {"component": "compressor_contactor", "issue": "welded_contacts",
             "onset_year": 7, "frequency": "16%"},
            {"component": "drain_pan", "issue": "algae_and_overflow",
             "onset_year": 5, "frequency": "21%",
             "regions": ["gulf_coast", "southeast"],
             "notes": "Annual pan treatments reduce callbacks significantly"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["RA14AZ-036JCZ"],
    },
    {
        "brand": "Rheem",
        "model_series": "R96V",
        "model_pattern": r"R96V\d{8}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2014-2024",
        "avg_lifespan_years": 22,
        "known_issues": [
            {"component": "inducer_motor", "issue": "condensate_in_windings",
             "onset_year": 8, "frequency": "10%",
             "notes": "Furnace installed in unconditioned space without drip shield"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RP20AZ",
        "model_pattern": r"RP20AZ-\d{3}JCZ",
        "equipment_type": "heat_pump",
        "seer_rating": 20.5,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2020-2024",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RPKA",
        "model_pattern": r"RPKA-\d{3}[A-Z]{3}",
        "equipment_type": "heat_pump",
        "seer_rating": 14.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2008-2020",
        "avg_lifespan_years": 14,
        "known_issues": [
            {"component": "reversing_valve", "issue": "solenoid_burnout",
             "onset_year": 8, "frequency": "12%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["RP14AZ-036JCZ"],
    },
    {
        "brand": "Rheem",
        "model_series": "RHMV",
        "model_pattern": r"RHMV\d{8}",
        "equipment_type": "air_handler",
        "seer_rating": None,
        "tonnage_range": "2-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "blower_motor_capacitor", "issue": "failure",
             "onset_year": 5, "frequency": "19%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "R92P",
        "model_pattern": r"R92P\d{8}",
        "equipment_type": "furnace",
        "seer_rating": None,
        "tonnage_range": None,
        "manufacture_years": "2010-2022",
        "avg_lifespan_years": 20,
        "known_issues": [
            {"component": "pressure_switch", "issue": "stuck_open",
             "onset_year": 5, "frequency": "15%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": ["R96V-0801317MSA"],
    },
    {
        "brand": "Rheem",
        "model_series": "RAPM",
        "model_pattern": r"RAPM-\d{3}[A-Z]{3}",
        "equipment_type": "packaged_unit",
        "seer_rating": 16.0,
        "tonnage_range": "2-5",
        "manufacture_years": "2012-2023",
        "avg_lifespan_years": 18,
        "known_issues": [],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
    {
        "brand": "Rheem",
        "model_series": "RA16AZ",
        "model_pattern": r"RA16AZ-\d{3}JCZ",
        "equipment_type": "ac_unit",
        "seer_rating": 17.0,
        "tonnage_range": "1.5-5",
        "manufacture_years": "2016-2024",
        "avg_lifespan_years": 17,
        "known_issues": [
            {"component": "fan_blade", "issue": "balance_noise",
             "onset_year": 4, "frequency": "8%"},
        ],
        "serial_decode_pattern": {},
        "replacement_models": [],
    },
]


from sqlalchemy import select, func

async def run():
    async with AsyncSessionLocal() as db:
        try:
            result = await db.execute(select(func.count()).select_from(EquipmentModel))
            existing_count = result.scalar()
            if existing_count > 0:
                print(f"⚠  {existing_count} equipment models already exist — skipping to avoid duplicates.")
                print("   To re-seed, delete existing rows first or run with --force")
                return

            print(f"Seeding {len(EQUIPMENT_MODELS)} equipment models…")
            for m in EQUIPMENT_MODELS:
                model = EquipmentModel(
                    brand=m["brand"],
                    model_series=m["model_series"],
                    model_pattern=m.get("model_pattern"),
                    equipment_type=m["equipment_type"],
                    seer_rating=m.get("seer_rating"),
                    tonnage_range=m.get("tonnage_range"),
                    manufacture_years=m.get("manufacture_years"),
                    avg_lifespan_years=m.get("avg_lifespan_years"),
                    known_issues=m.get("known_issues"),
                    serial_decode_pattern=m.get("serial_decode_pattern"),
                    replacement_models=m.get("replacement_models"),
                    total_assessments=0,
                )
                db.add(model)

            await db.commit()
            print(f"✅ {len(EQUIPMENT_MODELS)} equipment models seeded successfully.")

        except Exception as e:
            await db.rollback()
            print(f"❌ Seed failed: {e}")
            raise


if __name__ == "__main__":
    asyncio.run(run())
